using Serenity.Navigation;
using MyPages = LBYS.Lab.Pages;

[assembly: NavigationLink(int.MaxValue, "Lab/Laboratory", typeof(MyPages.LaboratoryController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Lab/Doctor", typeof(MyPages.DoctorController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Lab/Template", typeof(MyPages.TemplateController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Lab/Report", typeof(MyPages.ReportController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Lab/User Laboratory", typeof(MyPages.UserLaboratoryController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Lab/Material", typeof(MyPages.MaterialController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Lab/Tube", typeof(MyPages.TubeController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Lab/Unit", typeof(MyPages.UnitController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Lab/Sut", typeof(MyPages.SutController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Lab/Assay", typeof(MyPages.AssayController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Lab/Assay Result", typeof(MyPages.AssayResultController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Lab/Lek", typeof(MyPages.LekController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Lab/Device", typeof(MyPages.DeviceController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Lab/Code", typeof(MyPages.CodeController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Lab/Levels", typeof(MyPages.LevelsController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Lab/Control", typeof(MyPages.ControlController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Lab/Reference", typeof(MyPages.ReferenceController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Lab/Description", typeof(MyPages.DescriptionController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Lab/Industry", typeof(MyPages.IndustryController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Lab/Institution", typeof(MyPages.InstitutionController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Lab/Institution Doctor", typeof(MyPages.InstitutionDoctorController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Lab/User Institution", typeof(MyPages.UserInstitutionController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Lab/Institution Panel", typeof(MyPages.InstitutionPanelController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Lab/Institution Panel Assay", typeof(MyPages.InstitutionPanelAssayController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Lab/User Unit", typeof(MyPages.UserUnitController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Lab/Panel", typeof(MyPages.PanelController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Lab/Panel Assay", typeof(MyPages.PanelAssayController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Lab/Patient", typeof(MyPages.PatientController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Lab/Invoice", typeof(MyPages.InvoiceController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Lab/Claim", typeof(MyPages.ClaimController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Lab/Sample", typeof(MyPages.SampleController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Lab/Detail", typeof(MyPages.DetailController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Lab/Change", typeof(MyPages.ChangeController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Lab/Image", typeof(MyPages.ImageController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Lab/Bacterium", typeof(MyPages.BacteriumController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Lab/Antibiogram", typeof(MyPages.AntibiogramController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Lab/Accept", typeof(MyPages.AcceptController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Lab/Notification", typeof(MyPages.NotificationController), icon: null)]